"""Generate a runnable notebook for MR or EMA directional-controller sweeps.

Usage:
    python create_sweep_nb_directional.py --strategy mr --connector nonkyc \
        --trading-pair XMR-USDT --interval 5m --n-trials 200 \
        --study-name xmr_mr_v1 --out-dir notebooks/sweep

For EMA, also pass --regime-interval 4h.

The generated notebook:
  1. Loads candles from MongoDB via MongoCandleLoader.
  2. **HARD-STOP preflight**: validate_candles(strict=True) on every interval.
  3. Soft warning for XMR-USDT rule presence (resolved default vs override).
  4. Builds an objective via create_objective(strategy_name=...).
  5. Runs an Optuna study for n_trials.
  6. Exports the best trial's canonicalized config to YAML.
  7. Reports holdout, recent-window, stress, informational gates.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List


def _make_notebook_cells(
    strategy: str,
    connector: str,
    trading_pair: str,
    interval: str,
    regime_interval: str,
    n_trials: int,
    study_name: str,
    objective_version: int,
) -> List[Dict]:
    """Build a list of .ipynb cells for the given strategy."""
    is_ema = strategy == "ema"
    title_name = "EMA regime-hold" if is_ema else "mean-reversion BB+RSI"
    strategy_key = "ema_regime_hold" if is_ema else "mean_reversion_bb_rsi"
    canonical_controller = "ema_regime_hold_v1" if is_ema else "mean_reversion_bb_rsi_v1"

    cells = []

    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            f"# {title_name} sweep — {connector} {trading_pair} {interval}\n",
            "\n",
            "Generated by `create_sweep_nb_directional.py`. See the module docstring for semantics.\n",
            "\n",
            f"- Strategy: `{strategy_key}`\n",
            f"- Connector/Pair: `{connector}:{trading_pair}`\n",
            f"- Signal interval: `{interval}`\n",
            (f"- Regime interval: `{regime_interval}`\n" if is_ema else ""),
            f"- Study: `{study_name}`\n",
            f"- Trials: `{n_trials}`\n",
        ],
    })

    cells.append({
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "import os\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import optuna\n",
            "from pathlib import Path\n",
            "from pmm_lab.data.mongo import MongoCandleLoader\n",
            "from pmm_lab.config.params import DataQuery\n",
            "from pmm_lab.data.candles import validate_candles\n",
            "from pmm_lab.config.exchange_rules import load_exchange_rules, resolve_pair_rules\n",
            "from pmm_lab.data.hashing import hash_candles\n",
            "from pmm_lab.optuna.objective_wrapper import create_objective\n",
        ],
    })

    cells.append({
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            f"CONNECTOR = {connector!r}\n",
            f"TRADING_PAIR = {trading_pair!r}\n",
            f"SIGNAL_INTERVAL = {interval!r}\n",
            (f"REGIME_INTERVAL = {regime_interval!r}\n" if is_ema else ""),
            f"N_TRIALS = {n_trials}\n",
            f"STUDY_NAME = {study_name!r}\n",
            f"OBJECTIVE_VERSION = {objective_version}\n",
            f"STRATEGY_NAME = {strategy_key!r}\n",
            f"CONTROLLER_NAME = {canonical_controller!r}\n",
            "ARTIFACTS_DIR = Path('artifacts') / STUDY_NAME\n",
            "ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)\n",
        ],
    })

    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## Load candles from Mongo"],
    })

    cells.append({
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "loader = MongoCandleLoader()\n",
            "candles = loader.load_range(DataQuery(\n",
            "    connector=CONNECTOR, trading_pair=TRADING_PAIR,\n",
            "    interval=SIGNAL_INTERVAL, start_ts=None,\n",
            "))\n",
            "print(f'Loaded {len(candles)} {SIGNAL_INTERVAL} bars')\n",
            (
                "regime_candles = loader.load_range(DataQuery(\n"
                "    connector=CONNECTOR, trading_pair=TRADING_PAIR,\n"
                "    interval=REGIME_INTERVAL, start_ts=None,\n"
                "))\n"
                "print(f'Loaded {len(regime_candles)} {REGIME_INTERVAL} bars')\n"
                if is_ema else ""
            ),
        ],
    })

    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## HARD-STOP preflight: dataset audit\n",
            "If `passed_strict` is False, the cell raises and the notebook halts.\n",
        ],
    })

    cells.append({
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "audit_signal = validate_candles(candles, SIGNAL_INTERVAL, strict=True)\n",
            "if not audit_signal.passed_strict:\n",
            "    print('FAIL (signal):')\n",
            "    print('  failure_reasons:', audit_signal.failure_reasons)\n",
            "    print('  dataset_hash:', hash_candles(candles))\n",
            "    print('  first_ts:', int(candles[0]['timestamp']), 'last_ts:', int(candles[-1]['timestamp']))\n",
            "    raise RuntimeError('Signal candles failed strict audit — halting (HARD STOP)')\n",
            "print('Signal candles PASSED strict audit')\n",
            (
                "audit_regime = validate_candles(regime_candles, REGIME_INTERVAL, strict=True)\n"
                "if not audit_regime.passed_strict:\n"
                "    print('FAIL (regime):', audit_regime.failure_reasons)\n"
                "    raise RuntimeError('Regime candles failed strict audit — halting (HARD STOP)')\n"
                "print('Regime candles PASSED strict audit')\n"
                if is_ema else ""
            ),
        ],
    })

    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Soft preflight: XMR-USDT pair rule presence\n",
            "Warn if the resolved rules fell back to the connector default.",
        ],
    })

    cells.append({
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "rules_data = load_exchange_rules()\n",
            "_conn = rules_data['connectors'][CONNECTOR]\n",
            "has_override = TRADING_PAIR in _conn.get('pairs', {})\n",
            "pair_rules = resolve_pair_rules(rules_data, CONNECTOR, TRADING_PAIR)\n",
            "if not has_override:\n",
            "    print(f'WARNING: no per-pair override for {CONNECTOR}:{TRADING_PAIR} — using defaults')\n",
            "print('price_tick:', pair_rules.price_tick, 'amount_step:', pair_rules.amount_step,\n",
            "      'min_notional_quote:', pair_rules.min_notional_quote)\n",
        ],
    })

    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## Build objective and run Optuna"],
    })

    objective_lines = [
        "from pmm_lab.config.defaults import INTERVAL_SECONDS\n",
        "bar_interval_seconds = INTERVAL_SECONDS[SIGNAL_INTERVAL]\n",
        "reference_price = float(candles['close'][-1])\n",
        "dataset_hash = hash_candles(candles)\n",
        "objective = create_objective(\n",
        "    candles=candles,\n",
        "    pair_rules=pair_rules,\n",
        "    bar_interval_seconds=bar_interval_seconds,\n",
        "    dataset_hash=dataset_hash,\n",
        "    reference_price=reference_price,\n",
        "    train_days=42.0, test_days=14.0, step_days=14.0,\n",
        "    strategy_name=STRATEGY_NAME,\n",
        "    objective_version=OBJECTIVE_VERSION,\n",
        "    run_stress=True,\n",
        "    controller_compat=False,\n",
    ]
    if is_ema:
        objective_lines.append("    regime_candles=regime_candles,\n")
    objective_lines.extend([
        ")\n",
        "study = optuna.create_study(direction='maximize', study_name=STUDY_NAME)\n",
        "study.optimize(objective, n_trials=N_TRIALS)\n",
    ])
    cells.append({
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": objective_lines,
    })

    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## Export best trial to YAML"],
    })

    if is_ema:
        export_snippet = [
            "from pmm_lab.export.hb_yaml_ema_regime_hold import (\n",
            "    EMARegimeHoldExportParams, export_ema_regime_hold_yaml, validate_export_ema_regime_hold,\n",
            ")\n",
            "from pmm_lab.optuna.canonicalizer_ema_regime_hold import canonicalize_ema_regime_hold_params\n",
            "best = max(\n",
            "    (t for t in study.trials if t.state == optuna.trial.TrialState.COMPLETE and t.user_attrs.get('reject_reason') is None),\n",
            "    key=lambda t: t.user_attrs.get('objective_score', float('-inf')),\n",
            "    default=None,\n",
            ")\n",
            "assert best is not None, 'No completed trials'\n",
            "raw = dict(best.params)\n",
            "# Inject fixed values that the canonicalizer expects\n",
            "raw.setdefault('hold_mode', 'reentry')\n",
            "raw.setdefault('max_executors_per_side', 1)\n",
            "bundle, reason = canonicalize_ema_regime_hold_params(\n",
            "    raw, pair_rules, reference_price,\n",
            "    signal_interval_seconds=bar_interval_seconds,\n",
            "    regime_candles=regime_candles,\n",
            ")\n",
            "assert bundle is not None, reason\n",
            "export_params = EMARegimeHoldExportParams(\n",
            "    connector_name=CONNECTOR, trading_pair=TRADING_PAIR,\n",
            "    signal_interval=SIGNAL_INTERVAL, regime_interval=REGIME_INTERVAL,\n",
            ")\n",
            "out_path = ARTIFACTS_DIR / f'{CONNECTOR}_{TRADING_PAIR.replace(\"-\", \"_\").lower()}_{CONTROLLER_NAME}.yml'\n",
            "export_ema_regime_hold_yaml(bundle.strategy_config, bundle.engine_config, export_params, out_path)\n",
            "validate_export_ema_regime_hold(out_path)\n",
            "print('Exported:', out_path)\n",
        ]
    else:
        export_snippet = [
            "from pmm_lab.export.hb_yaml_mr_bb_rsi import (\n",
            "    MRBBRSIExportParams, export_mr_bb_rsi_yaml, validate_export_mr_bb_rsi,\n",
            ")\n",
            "from pmm_lab.optuna.canonicalizer_mean_reversion_bb_rsi import canonicalize_mr_bb_rsi_params\n",
            "best = max(\n",
            "    (t for t in study.trials if t.state == optuna.trial.TrialState.COMPLETE and t.user_attrs.get('reject_reason') is None),\n",
            "    key=lambda t: t.user_attrs.get('objective_score', float('-inf')),\n",
            "    default=None,\n",
            ")\n",
            "assert best is not None, 'No completed trials'\n",
            "raw = dict(best.params)\n",
            "raw.setdefault('min_trend_slope', 0.0)  # D17\n",
            "raw.setdefault('max_spread_pct', 0.006)\n",
            "raw.setdefault('max_trades_per_day', 6)\n",
            "raw.setdefault('max_executors_per_side', 1)\n",
            "bundle, reason = canonicalize_mr_bb_rsi_params(\n",
            "    raw, pair_rules, reference_price, bar_interval_seconds=bar_interval_seconds,\n",
            ")\n",
            "assert bundle is not None, reason\n",
            "export_params = MRBBRSIExportParams(\n",
            "    connector_name=CONNECTOR, trading_pair=TRADING_PAIR, interval=SIGNAL_INTERVAL,\n",
            ")\n",
            "out_path = ARTIFACTS_DIR / f'{CONNECTOR}_{TRADING_PAIR.replace(\"-\", \"_\").lower()}_{CONTROLLER_NAME}.yml'\n",
            "export_mr_bb_rsi_yaml(bundle.strategy_config, bundle.engine_config, export_params, out_path)\n",
            "validate_export_mr_bb_rsi(out_path)\n",
            "print('Exported:', out_path)\n",
        ]

    cells.append({
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": export_snippet,
    })

    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Release gates — informational only\n",
            "Per user directive, only the data-audit gate hard-stops. All other gates are reported but not enforced.",
        ],
    })

    cells.append({
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "# Soft gates compute pass/fail but do not short-circuit.\n",
            "robust_score = float(best.user_attrs.get('objective_score', 0.0))\n",
            "worst_stress = float(best.user_attrs.get('stress_worst_score', 0.0))\n",
            "trade_count = float(best.user_attrs.get('trade_count_median', 0.0))\n",
            "gates = [\n",
            "    ('robust score > 0',               robust_score, 0.0, robust_score > 0),\n",
            "    ('worst stress score > -10',        worst_stress, -10.0, worst_stress > -10),\n",
            "    ('trade_count_median >= 3',         trade_count, 3.0, trade_count >= 3),\n",
            "]\n",
            "print('Release Gates (Informational Only)')\n",
            "for name, actual, threshold, passed in gates:\n",
            "    mark = 'PASS' if passed else 'FAIL'\n",
            "    print(f'  [{mark}] {name}: actual={actual} threshold={threshold}')\n",
            "# Exported YAML is produced regardless of gate status.\n",
        ],
    })

    return cells


def build_notebook(
    strategy: str,
    connector: str,
    trading_pair: str,
    interval: str,
    regime_interval: str,
    n_trials: int,
    study_name: str,
    out_dir: Path,
    objective_version: int = 1,
) -> Path:
    """Build a .ipynb file and return its path."""
    cells = _make_notebook_cells(
        strategy=strategy,
        connector=connector,
        trading_pair=trading_pair,
        interval=interval,
        regime_interval=regime_interval,
        n_trials=n_trials,
        study_name=study_name,
        objective_version=objective_version,
    )
    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.12"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{study_name}.ipynb"
    with open(out_path, "w") as f:
        json.dump(notebook, f, indent=1)
    return out_path


def main():
    p = argparse.ArgumentParser(description="Generate an MR/EMA directional sweep notebook.")
    p.add_argument("--strategy", choices=["mr", "ema"], required=True)
    p.add_argument("--connector", required=True)
    p.add_argument("--trading-pair", required=True)
    p.add_argument("--interval", required=True)
    p.add_argument("--regime-interval", default="4h")
    p.add_argument("--n-trials", type=int, default=200)
    p.add_argument("--study-name", required=True)
    p.add_argument("--out-dir", default="notebooks/sweep")
    p.add_argument("--objective-version", type=int, default=1)
    args = p.parse_args()

    out_path = build_notebook(
        strategy=args.strategy,
        connector=args.connector,
        trading_pair=args.trading_pair,
        interval=args.interval,
        regime_interval=args.regime_interval,
        n_trials=args.n_trials,
        study_name=args.study_name,
        out_dir=Path(args.out_dir),
        objective_version=args.objective_version,
    )
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
