"""Assemble <run_dir>/report.md per [Report §13.12].

The report has 8 sections plus a suitability tier:
  1. Header / metadata
  2. Data quality
  3. Gate funnel
  4. Trade metrics
  5. Liquidity & execution
  6. MFE / MAE
  7. Cost stress comparison (if multi-run results passed)
  8. Delay sensitivity (if multi-run results passed)
Suitability tier: ``research_only`` / ``backtesting_only`` / ``paper_candidate`` /
``live_candidate``.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Literal

import pandas as pd

from .data_quality_section import render_data_quality_section


SUITABILITY_TIERS = ("research_only", "backtesting_only", "paper_candidate", "live_candidate")
SuitabilityTier = Literal["research_only", "backtesting_only", "paper_candidate", "live_candidate"]


def render_run_report(
    run_dir: Path,
    *,
    suitability: str,
    cost_stress_table: pd.DataFrame | None = None,
    delay_sensitivity_table: pd.DataFrame | None = None,
) -> str:
    """Render the report.md content for ``run_dir`` and return as a string.

    Raises ``ValueError`` if ``suitability`` is not one of the canonical tiers.
    """
    if suitability not in SUITABILITY_TIERS:
        raise ValueError(
            f"suitability must be one of {SUITABILITY_TIERS}, got {suitability!r}"
        )
    rd = Path(run_dir)
    summary = json.loads((rd / "summary.json").read_text(encoding="utf-8")) if (rd / "summary.json").is_file() else {}
    run_manifest = json.loads((rd / "run_manifest.json").read_text(encoding="utf-8")) if (rd / "run_manifest.json").is_file() else {}

    lines = [
        f"# Bowaka v2 Backtest Report",
        "",
        f"- **Suitability tier:** `{suitability}`",
        f"- run_id: `{run_manifest.get('run_id', summary.get('run_id', 'unknown'))}`",
        f"- strategy: `bowaka_v2` v{run_manifest.get('strategy_version', '0.1.0')}",
        f"- feed: `{summary.get('feed', 'unknown')}`",
        f"- cost_stress: `{summary.get('cost_stress', 'unknown')}`",
        f"- created_at: `{run_manifest.get('created_at', 'unknown')}`",
        "",
    ]
    # Section 1 (header) already above.
    lines.append("## Run Metrics")
    for k in ("n_trades", "win_rate", "total_pnl", "net_return_pct", "max_drawdown_pct",
                "candidate_events_count", "entry_decisions_count", "accepted_count",
                "rejected_count", "broker_reject_count", "ambiguous_bar_count"):
        lines.append(f"- {k}: {summary.get(k)}")
    lines.append("")

    lines.append(render_data_quality_section(rd))
    lines.append("")

    # Trade-metrics section header (table omitted in stub — extension in later iteration).
    lines.append("## Trade Metrics")
    lines.append("- See `trades.parquet` for per-trade detail.")
    lines.append("")

    lines.append("## Liquidity & Execution")
    lines.append("- See `entry_decisions.parquet` and `execution_quality.parquet`.")
    lines.append("")

    lines.append("## MFE / MAE")
    lines.append("- See `reports/mfe_mae.py` (called from notebooks).")
    lines.append("")

    # Realism Phase 7: exit-lifecycle analysis. Rendered from exit_analysis.json
    # (written by sim.backtester) when present.
    lines.append("## Exit Analysis")
    ea_path = rd / "exit_analysis.json"
    if ea_path.is_file():
        try:
            ea = json.loads(ea_path.read_text(encoding="utf-8"))
        except Exception:  # noqa: BLE001
            ea = {}
        dist = (ea.get("exit_reason_distribution") or {})
        counts = dist.get("counts") or {}
        slip = ea.get("exit_slippage_bps") or {}
        lines.append(f"- trades closed: {dist.get('n_trades', 0)}")
        lines.append(f"- ambiguous_stop_wins: {dist.get('ambiguous_stop_wins', 0)}")
        lines.append(
            "- exit-reason counts: "
            + ", ".join(f"{k}={v}" for k, v in counts.items())
        )
        lines.append(
            f"- exit-slippage bps: mean={slip.get('mean', 0)} "
            f"p95={slip.get('p95', 0)}"
        )
        lines.append(
            f"- signal-fade telemetry events: "
            f"{ea.get('signal_fade_telemetry_count', 0)}"
        )
    else:
        lines.append(
            "- Not available because: exit_analysis.json was not written for "
            "this run."
        )
    lines.append("")

    lines.append("## Gate Funnel")
    lines.append("- See `gate_dump.parquet` and `reports/gate_funnel.py`.")
    lines.append("")

    if cost_stress_table is not None and not cost_stress_table.empty:
        lines.append("## Cost-Stress Comparison")
        lines.append(cost_stress_table.to_markdown(index=False))
        lines.append("")
    if delay_sensitivity_table is not None and not delay_sensitivity_table.empty:
        lines.append("## Delay Sensitivity")
        lines.append(delay_sensitivity_table.to_markdown(index=False))
        lines.append("")

    lines.append("---")
    lines.append("*Generated by bowaka_v2_lab.reports.render_run_report*")
    return "\n".join(lines) + "\n"
