"""Generate frozen feature fixtures for MR BB+RSI and EMA regime-hold.

Fixtures live under fixtures/mr_short_100bar/ and fixtures/ema_short_100bar/ and
contain:
  - candles.npz (signal candles; regime_candles.npz for EMA)
  - expected_features.json (computed once by the current feature impl)
  - config_params.json
  - README.md explaining what generated the fixture

These are used by the parity gate to detect silent feature-implementation drift.
"""

import json
from pathlib import Path
import sys

import numpy as np


CANDLE_DTYPE = np.dtype([
    ("timestamp", "int64"),
    ("open", "float64"),
    ("high", "float64"),
    ("low", "float64"),
    ("close", "float64"),
    ("volume", "float64"),
    ("is_forward_fill", "bool"),
])


def _deterministic_candles(n: int, seed: int, start_ts: int = 1_700_000_000, dt: int = 60) -> np.ndarray:
    rng = np.random.default_rng(seed)
    bars = np.zeros(n, dtype=CANDLE_DTYPE)
    bars["timestamp"] = start_ts + np.arange(n) * dt
    price = 100.0 + np.cumsum(rng.normal(0, 0.3, n))
    bars["close"] = price
    bars["open"] = np.concatenate([[price[0]], price[:-1]])
    bars["high"] = np.maximum(bars["open"], bars["close"]) + rng.uniform(0.1, 0.5, n)
    bars["low"] = np.minimum(bars["open"], bars["close"]) - rng.uniform(0.1, 0.5, n)
    bars["volume"] = rng.uniform(1000, 5000, n)
    return bars


def _scalar(val):
    """Convert numpy scalars to Python float/bool for JSON serialization."""
    if hasattr(val, "item"):
        val = val.item()
    if isinstance(val, (bool,)):
        return bool(val)
    if isinstance(val, (int, float)):
        return float(val)
    return val


def generate_mr_fixture(out_dir: Path):
    from pmm_lab.features.mean_reversion_bb_rsi_features import (
        compute_mr_bb_rsi_features, MRBBRSIFeatureConfig,
    )
    out_dir.mkdir(parents=True, exist_ok=True)
    candles = _deterministic_candles(100, seed=42)
    config_params = {
        "bb_length": 20, "bb_std": 2.0, "bbp_entry_threshold": 0.15,
        "rsi_length": 14, "rsi_entry_threshold": 35.0,
        "use_trend_filter": False,
        "trend_ema_length": 50, "min_trend_slope": 0.0,
        "atr_length": 14, "max_atr_pct_for_entry": 0.05,
        "volume_filter_window": 30, "min_volume_quantile": 0.0,
        "timestamp_mode": "open", "controller_compat": True,
    }
    feat_cfg = MRBBRSIFeatureConfig(**config_params)
    features = compute_mr_bb_rsi_features(candles, feat_cfg)

    bars_to_fix = [30, 50, 70, 85, 95]
    expected = {}
    for b in bars_to_fix:
        if b >= len(candles):
            continue
        row = {}
        for fname in ("signal", "bbp", "rsi", "atr_pct", "ema_slope", "volume_ok"):
            arr = features.data.get(fname)
            if arr is None or b >= len(arr):
                continue
            val = arr[b]
            # NaN values are stored as null (JSON) and handled by _compare_fields
            if isinstance(val, (np.floating,)) and np.isnan(val):
                row[fname] = float("nan")
            else:
                row[fname] = _scalar(val)
        expected[str(b)] = row

    np.savez(out_dir / "candles.npz", candles=candles)
    with open(out_dir / "expected_features.json", "w", encoding="utf-8") as f:
        # Use allow_nan so NaN → "NaN" in JSON
        json.dump(expected, f, indent=2, default=str, allow_nan=True)
    with open(out_dir / "config_params.json", "w", encoding="utf-8") as f:
        json.dump(config_params, f, indent=2)
    (out_dir / "README.md").write_text(
        "MR BB+RSI frozen parity fixture. Generated by "
        "scripts/generate_directional_fixtures.py from a deterministic seed=42 "
        "candle series (100 bars). Update only when the feature implementation's "
        "intended semantics change.\n"
    )
    print(f"Wrote {out_dir}")


def generate_ema_fixture(out_dir: Path):
    from pmm_lab.features.ema_regime_hold_features import (
        compute_ema_regime_hold_features, EMARegimeHoldFeatureConfig,
    )
    out_dir.mkdir(parents=True, exist_ok=True)
    signal = _deterministic_candles(100, seed=42, dt=60)
    # Regime interval = 4x signal interval: 25 regime bars cover 100 signal bars
    regime = _deterministic_candles(25, seed=7, start_ts=int(signal[0]["timestamp"]), dt=240)

    config_params = {
        "regime_ema_fast": 5, "regime_ema_slow": 10,
        "regime_adx_length": 7, "regime_adx_threshold": 15.0,
        "volume_filter_window": 20, "min_volume_quantile": 0.0,
        "hold_mode": "reentry", "timestamp_mode": "open", "controller_compat": True,
    }
    feat_cfg = EMARegimeHoldFeatureConfig(**config_params)
    features = compute_ema_regime_hold_features(signal, regime, feat_cfg)

    bars_to_fix = [30, 50, 70, 85, 95]
    expected = {}
    for b in bars_to_fix:
        if b >= len(signal):
            continue
        row = {}
        for fname in ("signal", "trend_on", "vol_ok"):
            arr = features.data.get(fname)
            if arr is None or b >= len(arr):
                continue
            val = arr[b]
            if isinstance(val, (np.floating,)) and np.isnan(val):
                row[fname] = float("nan")
            else:
                row[fname] = _scalar(val)
        expected[str(b)] = row

    np.savez(out_dir / "candles.npz", candles=signal)
    np.savez(out_dir / "regime_candles.npz", candles=regime)
    with open(out_dir / "expected_features.json", "w", encoding="utf-8") as f:
        json.dump(expected, f, indent=2, default=str, allow_nan=True)
    with open(out_dir / "config_params.json", "w", encoding="utf-8") as f:
        json.dump(config_params, f, indent=2)
    (out_dir / "README.md").write_text(
        "EMA regime-hold frozen parity fixture. Generated by "
        "scripts/generate_directional_fixtures.py from deterministic seeds "
        "(signal=42, regime=7). Update only when feature semantics change.\n"
    )
    print(f"Wrote {out_dir}")


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    root = Path(__file__).resolve().parent.parent
    generate_mr_fixture(root / "fixtures" / "mr_short_100bar")
    generate_ema_fixture(root / "fixtures" / "ema_short_100bar")
