"""Directional parity: MR and EMA fixtures must exist and match current feature impls."""
from pathlib import Path
import json

import numpy as np
import pytest

FIX_ROOT = Path(__file__).resolve().parents[2] / "fixtures"


def test_mr_fixture_directory_exists():
    assert (FIX_ROOT / "mr_short_100bar").is_dir(), (
        "MR parity fixture must be generated by scripts/generate_directional_fixtures.py"
    )


def test_ema_fixture_directory_exists():
    assert (FIX_ROOT / "ema_short_100bar").is_dir(), (
        "EMA parity fixture must be generated by scripts/generate_directional_fixtures.py"
    )


def test_mr_fixture_has_expected_files():
    fx = FIX_ROOT / "mr_short_100bar"
    for name in ("candles.npz", "expected_features.json", "config_params.json", "README.md"):
        assert (fx / name).exists(), f"MR fixture missing {name}"


def test_ema_fixture_has_expected_files():
    fx = FIX_ROOT / "ema_short_100bar"
    for name in ("candles.npz", "regime_candles.npz", "expected_features.json",
                 "config_params.json", "README.md"):
        assert (fx / name).exists(), f"EMA fixture missing {name}"


def test_load_frozen_fixture_returns_regime_for_ema():
    from pmm_lab.parity.fixtures import load_frozen_fixture
    fx = load_frozen_fixture(str(FIX_ROOT / "ema_short_100bar"))
    assert fx.candles is not None
    assert fx.regime_candles is not None, "EMA fixture must include regime_candles"
    assert len(fx.regime_candles) > 0


def test_mr_parity_passes_on_fixture():
    from pmm_lab.parity.feature_parity import check_feature_parity_frozen_mr
    from pmm_lab.parity.fixtures import load_frozen_fixture
    fx = load_frozen_fixture(str(FIX_ROOT / "mr_short_100bar"))
    result = check_feature_parity_frozen_mr(fx.candles, fx.expected_features, fx.config_params)
    assert result.passed, (
        f"MR parity fixture must match current feature impl. "
        f"Mismatches: {result.mismatches[:5]} (of {len(result.mismatches)})"
    )


def test_ema_parity_passes_on_fixture():
    from pmm_lab.parity.feature_parity import check_feature_parity_frozen_ema
    from pmm_lab.parity.fixtures import load_frozen_fixture
    fx = load_frozen_fixture(str(FIX_ROOT / "ema_short_100bar"))
    assert fx.regime_candles is not None, "EMA fixture must include regime_candles.npz"
    result = check_feature_parity_frozen_ema(
        fx.candles, fx.regime_candles, fx.expected_features, fx.config_params,
    )
    assert result.passed, (
        f"EMA parity fixture must match current feature impl. "
        f"Mismatches: {result.mismatches[:5]} (of {len(result.mismatches)})"
    )


def test_mr_parity_detects_field_change():
    """Perturbing an expected field must make parity fail."""
    from pmm_lab.parity.feature_parity import check_feature_parity_frozen_mr
    from pmm_lab.parity.fixtures import load_frozen_fixture
    fx = load_frozen_fixture(str(FIX_ROOT / "mr_short_100bar"))
    # Copy and perturb one field
    import copy
    bad = copy.deepcopy(fx.expected_features)
    # Find first non-nan numeric field in the first bar; flip it
    for bar_str, row in bad.items():
        for fname in row:
            val = row[fname]
            if isinstance(val, (int, float)) and not (isinstance(val, float) and val != val):
                row[fname] = val + 999.0
                break
        break
    result = check_feature_parity_frozen_mr(fx.candles, bad, fx.config_params)
    assert not result.passed
    assert len(result.mismatches) >= 1
